version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo Installing source NPM dependencies...
      - echo Install node version manager by typing the following at the command line.
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - echo Activate nvm by typing the following at the command line.
      - . ~/.nvm/nvm.sh
      - npm install 16
      - npm install express dotenv express-handlebars body-parser mysql
      - npm install --save-dev nodemon
      - npm install pm2@latest -g
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - buildspec.yml
    - /AWS-FCJ-Management/*
    - '**/*'